name: Auto Deploy on Push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      # - name: "Checkout production branch"
      #   uses: actions/checkout@v3
      #   with:
      #     ref: prod
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Stop the server
        run: ssh staging 'cd twofivefour && docker compose down'
      - name: Start the server
        run: ssh staging 'cd twofivefour && docker compose up -d'
